/**
 * Sidebar configuration for Community docs (unversioned)
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  communitySidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      label: '🔐 Members Only',
      href: 'https://app.charmverse.io/creative-like-brown-fowl/',
      className: 'charmverse',
      description: 'A multi-faceted platform catering to various needs in the Web3 space, from task management to professional networking and community engagement.',
    },
  ],
};

module.exports = sidebars;
